/**
 * Owner-approved product SEO metadata.
 * Current slice: A+B+CP1 (123)
 * Sources: Product Batch A/B + MaisonDeSon_Commercial_Product_Remaining_230.xlsx
 * + MaisonDeSon_Commercial_SEO_Master_V12.xlsx
 * Do NOT rewrite Final_* strings — copy-only implementation map.
 * Keyed by stable Product_ID. Extend only; never replace completed entries.
 */

import { resolveProductId } from '@/lib/productEntity';

export type ProductSeoMetadata = {
  title: string;
  description: string;
  h1: string;
  canonical: string;
  urlPath: string;
  concentration?: string;
  notesUsed?: string;
  scentDirection?: string;
};

/** Product_ID → approved commercial SEO metadata (123 entries) */
export const PRODUCT_SEO_METADATA: Record<string, ProductSeoMetadata> = {
  // ── COMMERCIAL_V9_PRODUCTS_A_23 ──────────────────────────────────────
  "montblanc-signature-edp": {
    title: `Montblanc Signature EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Montblanc Signature EDP hòa vani mềm, xạ hương trắng và cam clementine; xem review, giá tham khảo và tiêu chí chọn nơi mua hàng chính hãng.`,
    h1: `Montblanc Signature EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-montblanc-montblanc-signature-edp`,
    urlPath: `/nuoc-hoa-nu-montblanc-montblanc-signature-edp`,
    concentration: `Eau de Parfum`,
  },
  "24-faubourg": {
    title: `Hermès 24 Faubourg EDP chính hãng: giá và review`,
    description: `Hermès 24 Faubourg EDP kết hợp hoa cam, nhài, hổ phách và vani; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua hàng chính hãng.`,
    h1: `Hermès 24 Faubourg EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-hermes-24-faubourg`,
    urlPath: `/nuoc-hoa-nu-hermes-24-faubourg`,
    concentration: `EDP`,
  },
  "9pm": {
    title: `Afnan 9PM EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Afnan 9PM EDP đi theo hướng ngọt, trẻ và dễ gây chú ý; xem review, giá tham khảo, lưu ý thật giả và tiêu chí chọn nơi mua chính hãng.`,
    h1: `Afnan 9PM EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-afnan-9pm`,
    urlPath: `/nuoc-hoa-nam-afnan-9pm`,
    concentration: `EDP`,
  },
  "absolu-aventus": {
    title: `Creed Absolu Aventus EDP chính hãng: giá và review`,
    description: `Creed Absolu Aventus EDP nhấn vào quế và gỗ tuyết tùng theo hướng ấm, sâu; xem review, giá tham khảo và tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Creed Absolu Aventus EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-creed-absolu-aventus`,
    urlPath: `/nuoc-hoa-nam-creed-absolu-aventus`,
    concentration: `EDP`,
    notesUsed: `quế, gỗ tuyết tùng`,
    scentDirection: `ấm và sâu`,
  },
  "acqua-di-gio": {
    title: `Giorgio Armani Acqua di Giò EDT chính hãng: giá và review`,
    description: `Acqua di Giò EDT nổi bật với cam bergamot, chanh xanh và hương biển tươi khoáng; xem giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Giorgio Armani Acqua di Giò EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-giorgio-armani-acqua-di-gio`,
    urlPath: `/nuoc-hoa-nam-giorgio-armani-acqua-di-gio`,
    concentration: `EDT`,
    notesUsed: `chanh, chanh xanh, cam bergamot, hương biển`,
    scentDirection: `tươi khoáng`,
  },
  "acqua-di-gio-parfum": {
    title: `Acqua di Giò Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Acqua di Giò Parfum kết hợp hương biển, trầm hương và hoắc hương theo hướng sâu hơn; xem giá tham khảo và tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Giorgio Armani Acqua di Giò Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-giorgio-armani-acqua-di-gio-parfum`,
    urlPath: `/nuoc-hoa-nam-giorgio-armani-acqua-di-gio-parfum`,
    concentration: `Parfum`,
    notesUsed: `trầm hương, hoắc hương, hương biển`,
    scentDirection: `tươi khoáng`,
  },
  "acqua-di-gio-profondo": {
    title: `Acqua di Giò Profondo EDP chính hãng: giá và review`,
    description: `Acqua di Giò Profondo EDP khai thác hương biển, quýt và sắc khoáng tươi mát; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Giorgio Armani Acqua di Giò Profondo EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-giorgio-armani-acqua-di-gio-profondo`,
    urlPath: `/nuoc-hoa-nam-giorgio-armani-acqua-di-gio-profondo`,
    concentration: `EDP (2020)`,
    notesUsed: `hương biển, quýt, khoáng chất`,
    scentDirection: `tươi khoáng`,
  },
  "acqua-di-gio-profumo": {
    title: `Acqua di Giò Profumo chính hãng: giá và mua ở đâu?`,
    description: `Acqua di Giò Profumo phối hương biển với trầm hương theo hướng tối và nam tính; xem review, giá tham khảo và lưu ý khi chọn nguồn mua chính hãng.`,
    h1: `Giorgio Armani Acqua di Giò Profumo Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-giorgio-armani-acqua-di-gio-profumo`,
    urlPath: `/nuoc-hoa-nam-giorgio-armani-acqua-di-gio-profumo`,
    concentration: `Parfum`,
    notesUsed: `hương biển, trầm hương`,
    scentDirection: `tươi khoáng`,
  },
  "addict-edp": {
    title: `Dior Addict EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Addict EDP kết hợp hoa nhài với vani theo hướng ấm, mềm và đậm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua hàng chính hãng.`,
    h1: `Dior Addict EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-dior-addict-edp`,
    urlPath: `/nuoc-hoa-nu-dior-addict-edp`,
    concentration: `EDP`,
    notesUsed: `hoa nhài, vani`,
    scentDirection: `ấm và mềm`,
  },
  "african-leather": {
    title: `Memo Paris African Leather EDP chính hãng: giá và review`,
    description: `African Leather EDP nổi bật với da thuộc, bạch đậu khấu và hoắc hương cay khô; xem giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Memo Paris African Leather EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-memo-african-leather`,
    urlPath: `/nuoc-hoa-unisex-memo-african-leather`,
    concentration: `EDP`,
    notesUsed: `da thuộc, bạch đậu khấu, hoắc hương`,
    scentDirection: `gỗ–cay sâu`,
  },
  "alexandria-ii": {
    title: `Xerjoff Alexandria II EDP chính hãng: giá và review`,
    description: `Alexandria II EDP kết hợp oải hương, trầm hương và vani theo hướng ấm, sâu; xem review, giá tham khảo và tiêu chí chọn nơi mua chính hãng.`,
    h1: `Xerjoff Alexandria II EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-xerjoff-alexandria-ii`,
    urlPath: `/nuoc-hoa-unisex-xerjoff-alexandria-ii`,
    concentration: `EDP`,
    notesUsed: `oải hương, trầm hương, vani`,
    scentDirection: `ấm và sâu`,
  },
  "alien-edp": {
    title: `Mugler Alien EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Mugler Alien EDP tập trung vào hoa nhài và hổ phách theo hướng đậm, ấm và dễ nhận biết; xem giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Mugler Alien EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-mugler-alien-edp`,
    urlPath: `/nuoc-hoa-nu-mugler-alien-edp`,
    concentration: `EDP`,
    notesUsed: `hoa nhài, hổ phách`,
    scentDirection: `ấm và mềm`,
  },
  "allure-edp": {
    title: `Chanel Allure EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Chanel Allure EDP hòa cam quýt, đào và vani theo hướng thanh lịch, ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Chanel Allure EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-chanel-allure-edp`,
    urlPath: `/nuoc-hoa-nu-chanel-allure-edp`,
    concentration: `EDP`,
    notesUsed: `cam, quýt, đào, vani`,
    scentDirection: `ngọt ấm`,
  },
  "allure-homme-edition-blanche": {
    title: `Chanel Allure Homme Édition Blanche chính hãng: giá và review`,
    description: `Allure Homme Édition Blanche EDP nổi bật với sắc chanh kem và gỗ mềm; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua Chanel chính hãng.`,
    h1: `Chanel Allure Homme Édition Blanche EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-chanel-allure-homme-edition-blanche`,
    urlPath: `/nuoc-hoa-nam-chanel-allure-homme-edition-blanche`,
    concentration: `EDP`,
    notesUsed: `chanh`,
    scentDirection: `có cá tính riêng`,
  },
  "allure-homme-edt": {
    title: `Chanel Allure Homme EDT chính hãng: giá và mua ở đâu?`,
    description: `Chanel Allure Homme EDT theo phong cách ấm, lịch sự và cổ điển; xem review, giá tham khảo cùng tiêu chí chọn nơi mua hàng chính hãng.`,
    h1: `Chanel Allure Homme EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-chanel-allure-homme-edt`,
    urlPath: `/nuoc-hoa-nam-chanel-allure-homme-edt`,
    concentration: `EDT`,
  },
  "allure-homme-sport": {
    title: `Chanel Allure Homme Sport EDT chính hãng: giá và review`,
    description: `Allure Homme Sport EDT kết hợp cam quýt với hương biển theo hướng tươi và năng động; xem giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Chanel Allure Homme Sport EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-chanel-allure-homme-sport`,
    urlPath: `/nuoc-hoa-nam-chanel-allure-homme-sport`,
    concentration: `EDT`,
    notesUsed: `cam, quýt, hương biển`,
    scentDirection: `tươi khoáng`,
  },
  "allure-homme-sport-eau-extreme": {
    title: `Chanel Allure Homme Sport Eau Extrême: giá và review chính hãng`,
    description: `Allure Homme Sport Eau Extrême nhấn vào đậu tonka theo hướng ấm, mượt và thể thao; xem giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Chanel Allure Homme Sport Eau Extrême`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-chanel-allure-homme-sport-eau-extreme`,
    urlPath: `/nuoc-hoa-nam-chanel-allure-homme-sport-eau-extreme`,
    concentration: `Eau Extrême`,
    notesUsed: `đậu tonka`,
    scentDirection: `ấm và mềm`,
  },
  "althair": {
    title: `Parfums de Marly Althaïr EDP chính hãng: giá và review`,
    description: `Althaïr EDP kết hợp quế, vani và sắc praline theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua hàng chính hãng.`,
    h1: `Parfums de Marly Althaïr EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-parfums-de-marly-althair`,
    urlPath: `/nuoc-hoa-nam-parfums-de-marly-althair`,
    concentration: `EDP`,
    notesUsed: `quế, vani, kẹo bông`,
    scentDirection: `ngọt ấm`,
  },
  "angel": {
    title: `Mugler Angel EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Mugler Angel EDP pha sô cô la, kẹo bông và hoắc hương theo hướng gourmand đậm; xem giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Mugler Angel EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-mugler-angel`,
    urlPath: `/nuoc-hoa-nu-mugler-angel`,
    concentration: `EDP`,
    notesUsed: `sô cô la, kẹo bông, hoắc hương, cỏ khô`,
    scentDirection: `ấm và sâu`,
  },
  "angel-muse": {
    title: `Mugler Angel Muse EDP chính hãng: giá và review`,
    description: `Angel Muse EDP kết hợp hạt dẻ, cacao và hoắc hương theo hướng ngọt, tối và béo; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Mugler Angel Muse EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-mugler-angel-muse`,
    urlPath: `/nuoc-hoa-nu-mugler-angel-muse`,
    concentration: `EDP`,
    notesUsed: `hạt dẻ, cacao, hoắc hương`,
    scentDirection: `ấm và sâu`,
  },
  "angelique-noire": {
    title: `Guerlain Angélique Noire EDP chính hãng: giá và review`,
    description: `Angélique Noire EDP đặt vani cạnh sắc xanh của bạch chỉ theo hướng mềm và khác biệt; xem giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Guerlain Angélique Noire EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-guerlain-angelique-noire`,
    urlPath: `/nuoc-hoa-unisex-guerlain-angelique-noire`,
    concentration: `EDP`,
    notesUsed: `vani`,
    scentDirection: `ấm và mềm`,
  },
  "angels-share": {
    title: `Kilian Angels’ Share EDP chính hãng: giá và review`,
    description: `Angels’ Share EDP kết hợp quế, vani và sắc rượu cognac theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Kilian Angels' Share EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-kilian-angels-share`,
    urlPath: `/nuoc-hoa-unisex-kilian-angels-share`,
    concentration: `EDP`,
    notesUsed: `quế, vani`,
    scentDirection: `ngọt ấm`,
  },
  "ani": {
    title: `Nishane Ani Extrait chính hãng: giá, review và mua ở đâu?`,
    description: `Nishane Ani Extrait phối vani, gừng và gỗ đàn hương theo hướng cay ấm, sâu; xem giá tham khảo cùng tiêu chí chọn nơi mua hàng chính hãng.`,
    h1: `Nishane Ani Extrait`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-nishane-ani`,
    urlPath: `/nuoc-hoa-unisex-nishane-ani`,
    concentration: `Extrait de Parfum`,
    notesUsed: `vani, gừng, gỗ đàn hương`,
    scentDirection: `gỗ–cay sâu`,
  },
  // ── COMMERCIAL_V10_PRODUCTS_B_23 ──────────────────────────────────────
  "antaeus": {
    title: `Chanel Antaeus EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Chanel Antaeus EDT kết hợp da thuộc và xạ hương theo hướng khô, sâu và cổ điển; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Chanel Antaeus EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-chanel-antaeus`,
    urlPath: `/nuoc-hoa-nam-chanel-antaeus`,
    concentration: `EDT`,
    notesUsed: `da thuộc, xạ hương`,
    scentDirection: `khô và sâu`,
  },
  "armani-si-edp": {
    title: `Giorgio Armani Sì EDP chính hãng: giá và review`,
    description: `Giorgio Armani Sì EDP hòa lý chua đen với vani theo hướng ấm, mềm và nữ tính; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Giorgio Armani Sì EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-giorgio-armani-armani-si-edp`,
    urlPath: `/nuoc-hoa-nu-giorgio-armani-armani-si-edp`,
    concentration: `EDP`,
    notesUsed: `lý chua đen, vani`,
    scentDirection: `ấm và mềm`,
  },
  "bal-dafrique": {
    title: `Byredo Bal d’Afrique EDP chính hãng: giá và review`,
    description: `Byredo Bal d’Afrique EDP theo phong cách trái cây sáng, phóng khoáng và hiện đại; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Byredo Bal d’Afrique EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-byredo-bal-dafrique`,
    urlPath: `/nuoc-hoa-unisex-byredo-bal-dafrique`,
    concentration: `EDP`,
  },
  "bianco-latte": {
    title: `Giardini di Toscana Bianco Latte EDP chính hãng: giá và review`,
    description: `Bianco Latte EDP kết hợp vani, mật ong và caramel theo hướng gourmand ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Giardini Di Toscana Bianco Latte EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-giardini-di-toscana-bianco-latte`,
    urlPath: `/nuoc-hoa-unisex-giardini-di-toscana-bianco-latte`,
    concentration: `EDP`,
    notesUsed: `vani, mật ong, caramel`,
    scentDirection: `ngọt ấm`,
  },
  "black-opium": {
    title: `YSL Black Opium EDP chính hãng: giá, review và mua ở đâu?`,
    description: `YSL Black Opium EDP kết hợp cà phê và vani theo hướng ngọt ấm, nổi bật; xem review, giá tham khảo và tiêu chí chọn nơi mua chính hãng.`,
    h1: `YSL Black Opium EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-ysl-black-opium`,
    urlPath: `/nuoc-hoa-nu-ysl-black-opium`,
    concentration: `EDP`,
    notesUsed: `cà phê, vani`,
    scentDirection: `ngọt ấm`,
  },
  "black-opium-le-parfum": {
    title: `YSL Black Opium Le Parfum chính hãng: giá và review`,
    description: `Black Opium Le Parfum tăng độ dày của vani bên cạnh cà phê và quế; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua YSL chính hãng.`,
    h1: `YSL Black Opium Le Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-ysl-black-opium-le-parfum`,
    urlPath: `/nuoc-hoa-nu-ysl-black-opium-le-parfum`,
    concentration: `Parfum`,
    notesUsed: `cà phê, vani, quế`,
    scentDirection: `ngọt ấm`,
  },
  "bleu-de-chanel-eau-de-parfum": {
    title: `Bleu de Chanel EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Bleu de Chanel EDP nổi bật với bưởi và trầm hương theo hướng khô, sâu và linh hoạt; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Chanel Bleu de Chanel Eau de Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-chanel-bleu-de-chanel-eau-de-parfum`,
    urlPath: `/nuoc-hoa-nam-chanel-bleu-de-chanel-eau-de-parfum`,
    concentration: `EDP`,
    notesUsed: `bưởi, trầm hương`,
    scentDirection: `khô và sâu`,
  },
  "bleu-de-chanel-parfum": {
    title: `Bleu de Chanel Parfum chính hãng: giá và review`,
    description: `Bleu de Chanel Parfum nhấn vào gỗ đàn hương theo hướng mượt, sâu và trưởng thành; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Chanel Bleu de Chanel Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-chanel-bleu-de-chanel-parfum`,
    urlPath: `/nuoc-hoa-nam-chanel-bleu-de-chanel-parfum`,
    concentration: `Parfum`,
    notesUsed: `gỗ đàn hương`,
    scentDirection: `khô và sâu`,
  },
  "bloom-edp": {
    title: `Gucci Bloom EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Gucci Bloom EDP tập trung vào hoa huệ theo hướng hoa trắng thanh lịch và nữ tính; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Gucci Bloom EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-gucci-bloom-edp`,
    urlPath: `/nuoc-hoa-nu-gucci-bloom-edp`,
    concentration: `EDP`,
    notesUsed: `hoa huệ`,
    scentDirection: `hoa thanh lịch`,
  },
  "bois-imperial": {
    title: `Essential Parfums Bois Impérial EDP chính hãng: giá và review`,
    description: `Bois Impérial EDP kết hợp Akigalawood và cỏ hương bài theo hướng gỗ khô, hiện đại; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Essential Parfums Bois Impérial EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-essential-parfums-bois-imperial`,
    urlPath: `/nuoc-hoa-unisex-essential-parfums-bois-imperial`,
    concentration: `EDP`,
    notesUsed: `gỗ Akigalawood, cỏ hương bài`,
    scentDirection: `khô và sâu`,
  },
  "born-in-roma-intense": {
    title: `Valentino Donna Born in Roma Intense EDP chính hãng: giá và review`,
    description: `Donna Born in Roma Intense EDP phối vani, hoa nhài và hổ phách theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Valentino Donna Born in Roma Intense EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-valentino-born-in-roma-intense`,
    urlPath: `/nuoc-hoa-nu-valentino-born-in-roma-intense`,
    concentration: `EDP`,
    notesUsed: `vani, hoa nhài, hổ phách`,
    scentDirection: `ngọt ấm`,
  },
  "boss-bottled-edp": {
    title: `Hugo Boss Boss Bottled EDP chính hãng: giá và review`,
    description: `Boss Bottled EDP kết hợp táo và quế theo hướng ấm, mềm và dễ dùng; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua Hugo Boss chính hãng.`,
    h1: `Hugo Boss Boss Bottled EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-hugo-boss-boss-bottled-edp`,
    urlPath: `/nuoc-hoa-nam-hugo-boss-boss-bottled-edp`,
    concentration: `EDP`,
    notesUsed: `táo, quế`,
    scentDirection: `ấm và mềm`,
  },
  "bottled-absolu": {
    title: `Hugo Boss Bottled Absolu chính hãng: giá và review`,
    description: `Bottled Absolu nhấn vào khói và da thuộc theo hướng khô, sâu và đậm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua Hugo Boss chính hãng.`,
    h1: `Hugo Boss Bottled Absolu EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-hugo-boss-bottled-absolu`,
    urlPath: `/nuoc-hoa-nam-hugo-boss-bottled-absolu`,
    concentration: `Parfum Intense`,
    notesUsed: `khói, da thuộc`,
    scentDirection: `khô và sâu`,
  },
  "carlisle": {
    title: `Parfums de Marly Carlisle EDP chính hãng: giá và review`,
    description: `Carlisle EDP kết hợp hoắc hương, táo, vani và nhục đậu khấu theo hướng gỗ cay sâu; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Parfums de Marly Carlisle EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-parfums-de-marly-carlisle`,
    urlPath: `/nuoc-hoa-unisex-parfums-de-marly-carlisle`,
    concentration: `EDP`,
    notesUsed: `hoắc hương, táo, vani, nhục đậu khấu`,
    scentDirection: `gỗ–cay sâu`,
  },
  "carnal-flower": {
    title: `Frederic Malle Carnal Flower EDP chính hãng: giá và review`,
    description: `Carnal Flower EDP tập trung vào hoa huệ trắng với sắc xanh mát của bạch đàn; xem review, giá tham khảo cùng tiêu chí chọn nơi mua Frederic Malle chính hãng.`,
    h1: `Frederic Malle Carnal Flower EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-frederic-malle-carnal-flower`,
    urlPath: `/nuoc-hoa-unisex-frederic-malle-carnal-flower`,
    concentration: `EDP`,
  },
  "champs-elysees-edp": {
    title: `Guerlain Champs-Élysées EDP chính hãng: giá và review`,
    description: `Champs-Élysées EDP nổi bật với hoa mimosa theo hướng hoa thanh lịch, sáng và dịu; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua Guerlain chính hãng.`,
    h1: `Guerlain Champs-Élysées EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-guerlain-champs-elysees-edp`,
    urlPath: `/nuoc-hoa-nu-guerlain-champs-elysees-edp`,
    concentration: `EDP`,
    notesUsed: `hoa mimosa`,
    scentDirection: `hoa thanh lịch`,
  },
  "chance-eau-tendre": {
    title: `Chanel Chance Eau Tendre EDP chính hãng: giá và review`,
    description: `Chance Eau Tendre EDP kết hợp bưởi và hoa nhài theo hướng hoa thanh lịch, tươi sáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua Chanel chính hãng.`,
    h1: `Chanel Chance Eau Tendre EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-chanel-chance-eau-tendre`,
    urlPath: `/nuoc-hoa-nu-chanel-chance-eau-tendre`,
    concentration: `EDP`,
    notesUsed: `bưởi, hoa nhài`,
    scentDirection: `hoa thanh lịch`,
  },
  "cinema": {
    title: `YSL Cinéma EDP chính hãng: giá, review và mua ở đâu?`,
    description: `YSL Cinéma EDP hòa hạnh nhân, cam clementine, vani và mơ theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `YSL Cinéma EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-ysl-cinema`,
    urlPath: `/nuoc-hoa-nu-ysl-cinema`,
    concentration: `EDP`,
    notesUsed: `hạnh nhân, cam clementine, vani, mơ`,
    scentDirection: `ngọt ấm`,
  },
  "ck-obsession": {
    title: `Calvin Klein Obsession for Men EDT chính hãng: giá và review`,
    description: `Calvin Klein Obsession for Men EDT theo phong cách ấm, đậm và cổ điển; xem review, giá tham khảo cùng tiêu chí chọn nơi mua hàng chính hãng.`,
    h1: `Calvin Klein Obsession for Men EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-calvin-klein-ck-obsession`,
    urlPath: `/nuoc-hoa-nam-calvin-klein-ck-obsession`,
    concentration: `EDT`,
  },
  "club-de-nuit-intense-man": {
    title: `Armaf Club de Nuit Intense Man Parfum: giá và review chính hãng`,
    description: `Club de Nuit Intense Man Parfum theo phong cách đậm, nam tính và dễ nhận biết; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua Armaf chính hãng.`,
    h1: `Club de Nuit Intense Man`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-armaf-club-de-nuit-intense-man`,
    urlPath: `/nuoc-hoa-nam-armaf-club-de-nuit-intense-man`,
    concentration: `Parfum`,
  },
  "coco-eau-de-parfum": {
    title: `Chanel Coco EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Chanel Coco EDP nhấn vào hổ phách theo hướng ấm, mềm và cổ điển; xem review, giá tham khảo cùng tiêu chí chọn nơi mua Chanel chính hãng.`,
    h1: `Chanel Coco Eau de Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-chanel-coco-eau-de-parfum`,
    urlPath: `/nuoc-hoa-nu-chanel-coco-eau-de-parfum`,
    concentration: `Eau de Parfum`,
    notesUsed: `hổ phách`,
    scentDirection: `ấm và mềm`,
  },
  "coco-eau-de-toilette": {
    title: `Chanel Coco EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Chanel Coco EDT phối hổ phách với trái cây theo hướng ngọt ấm và nhẹ hơn bản EDP; xem review, giá tham khảo cùng tiêu chí chọn nguồn mua chính hãng.`,
    h1: `Chanel Coco Eau de Toilette`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-chanel-coco-eau-de-toilette`,
    urlPath: `/nuoc-hoa-nu-chanel-coco-eau-de-toilette`,
    concentration: `Eau de Toilette`,
    notesUsed: `hổ phách, trái cây`,
    scentDirection: `ngọt ấm`,
  },
  "coco-mademoiselle-edp": {
    title: `Chanel Coco Mademoiselle EDP chính hãng: giá và review`,
    description: `Coco Mademoiselle EDP nổi bật với hoắc hương theo hướng khô, sâu và thanh lịch; xem review, giá tham khảo cùng tiêu chí chọn nơi mua Chanel chính hãng.`,
    h1: `Chanel Coco Mademoiselle EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-chanel-coco-mademoiselle-edp`,
    urlPath: `/nuoc-hoa-nu-chanel-coco-mademoiselle-edp`,
    concentration: `EDP`,
    notesUsed: `hoắc hương`,
    scentDirection: `khô và sâu`,
  },
  // ── COMMERCIAL_V12_PRODUCTS_CP1_77 ─────────────────────────────────────
  "coco-noir": {
    title: `Chanel Coco Noir EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Chanel Coco Noir EDP kết hợp nhũ hương và hoắc hương theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Chanel Coco Noir EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-chanel-coco-noir`,
    urlPath: `/nuoc-hoa-nu-chanel-coco-noir`,
    concentration: `EDP`,
    notesUsed: `nhũ hương, hoắc hương`,
    scentDirection: `khô và sâu`,
  },
  "code-parfum": {
    title: `Giorgio Armani Code Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Giorgio Armani Code Parfum nổi bật với diên vĩ và đậu tonka theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Giorgio Armani Code Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-giorgio-armani-code-parfum`,
    urlPath: `/nuoc-hoa-nam-giorgio-armani-code-parfum`,
    concentration: `Parfum`,
    notesUsed: `diên vĩ, đậu tonka`,
    scentDirection: `ấm và mềm`,
  },
  "colonia": {
    title: `Acqua di Parma Colonia EDC chính hãng: giá, review và mua ở đâu?`,
    description: `Acqua di Parma Colonia EDC phối cam và chanh theo hướng tươi sáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Acqua di Parma Colonia EDC`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-acqua-di-parma-colonia`,
    urlPath: `/nuoc-hoa-unisex-acqua-di-parma-colonia`,
    concentration: `EDC`,
    notesUsed: `cam, chanh`,
    scentDirection: `tươi sáng`,
  },
  "cool-water": {
    title: `Davidoff Cool Water EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Davidoff Cool Water EDT kết hợp hương biển và oải hương theo hướng tươi khoáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Davidoff Cool Water EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-davidoff-cool-water`,
    urlPath: `/nuoc-hoa-nam-davidoff-cool-water`,
    concentration: `EDT`,
    notesUsed: `hương biển, oải hương`,
    scentDirection: `tươi khoáng`,
  },
  "coromandel-eau-de-parfum": {
    title: `Chanel Coromandel EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Chanel Coromandel EDP nổi bật với hoắc hương và sô cô la theo hướng ấm và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Chanel Coromandel EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-chanel-coromandel-eau-de-parfum`,
    urlPath: `/nuoc-hoa-unisex-chanel-coromandel-eau-de-parfum`,
    concentration: `EDP`,
    notesUsed: `hoắc hương, sô cô la`,
    scentDirection: `ấm và sâu`,
  },
  "crystal-noir-eau-de-toilette": {
    title: `Versace Crystal Noir EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Versace Crystal Noir EDT phối dừa và lê theo hướng có cá tính riêng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Versace Crystal Noir EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-versace-crystal-noir-eau-de-toilette`,
    urlPath: `/nuoc-hoa-nu-versace-crystal-noir-eau-de-toilette`,
    concentration: `EDT`,
    notesUsed: `dừa, lê`,
    scentDirection: `có cá tính riêng`,
  },
  "dama-bianca": {
    title: `Xerjoff Dama Bianca EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Xerjoff Dama Bianca EDP kết hợp vani và hoa violet theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Xerjoff Dama Bianca EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-xerjoff-dama-bianca`,
    urlPath: `/nuoc-hoa-nu-xerjoff-dama-bianca`,
    concentration: `EDP`,
    notesUsed: `vani, hoa violet`,
    scentDirection: `ấm và mềm`,
  },
  "delina": {
    title: `Parfums de Marly Delina EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Parfums de Marly Delina EDP nổi bật với hoa hồng và quả vải theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Parfums de Marly Delina EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-parfums-de-marly-delina`,
    urlPath: `/nuoc-hoa-nu-parfums-de-marly-delina`,
    concentration: `EDP`,
    notesUsed: `hoa hồng, quả vải`,
    scentDirection: `ấm và mềm`,
  },
  "diorissimo": {
    title: `Diorissimo EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Diorissimo EDT phối hoa linh lan theo hướng hoa thanh lịch; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng trước khi quyết định.`,
    h1: `Diorissimo EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-dior-diorissimo`,
    urlPath: `/nuoc-hoa-nu-dior-diorissimo`,
    concentration: `EDT`,
    notesUsed: `hoa linh lan`,
    scentDirection: `hoa thanh lịch`,
  },
  "dolce-vita": {
    title: `Dior Dolce Vita EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Dolce Vita EDT kết hợp đào và quế theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng trước khi quyết định.`,
    h1: `Dior Dolce Vita EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-dior-dolce-vita`,
    urlPath: `/nuoc-hoa-nu-dior-dolce-vita`,
    concentration: `EDT`,
    notesUsed: `đào, quế`,
    scentDirection: `ngọt ấm`,
  },
  "drakkar-noir": {
    title: `Guy Laroche Drakkar Noir EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Guy Laroche Drakkar Noir EDT nổi bật với oải hương, rêu và rêu sồi theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Guy Laroche Drakkar Noir EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-guy-laroche-drakkar-noir`,
    urlPath: `/nuoc-hoa-nam-guy-laroche-drakkar-noir`,
    concentration: `EDT`,
    notesUsed: `oải hương, rêu, rêu sồi, da thuộc`,
    scentDirection: `khô và sâu`,
  },
  "dune-edt": {
    title: `Dior Dune EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Dune EDT phối hổ phách theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng trước khi quyết định.`,
    h1: `Dior Dune EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-dior-dune-edt`,
    urlPath: `/nuoc-hoa-nu-dior-dune-edt`,
    concentration: `EDT`,
    notesUsed: `hổ phách`,
    scentDirection: `ấm và mềm`,
  },
  "dylan-blue": {
    title: `Versace Pour Homme Dylan Blue EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Versace Pour Homme Dylan Blue EDT kết hợp hương thủy sinh, ambroxan và khói theo hướng tươi khoáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Versace Pour Homme Dylan Blue EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-versace-dylan-blue`,
    urlPath: `/nuoc-hoa-nam-versace-dylan-blue`,
    concentration: `EDT`,
    notesUsed: `hương thủy sinh, ambroxan, khói`,
    scentDirection: `tươi khoáng`,
  },
  "eau-de-parfum": {
    title: `Chloé EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Chloé EDP nổi bật với hoa hồng và hoa mẫu đơn theo hướng hoa rõ nét; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Chloé EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-chloe-eau-de-parfum`,
    urlPath: `/nuoc-hoa-nu-chloe-eau-de-parfum`,
    concentration: `EDP`,
    notesUsed: `hoa hồng, hoa mẫu đơn`,
    scentDirection: `hoa rõ nét`,
  },
  "eau-sauvage": {
    title: `Dior Eau Sauvage EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Eau Sauvage EDT phối cam và chanh theo hướng tươi sáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Dior Eau Sauvage EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-dior-eau-sauvage`,
    urlPath: `/nuoc-hoa-nam-dior-eau-sauvage`,
    concentration: `EDT`,
    notesUsed: `cam, chanh`,
    scentDirection: `tươi sáng`,
  },
  "eau-sauvage-parfum": {
    title: `Dior Eau Sauvage Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Eau Sauvage Parfum được đánh giá theo phong cách mùi, độ dễ dùng và hoàn cảnh phù hợp; xem giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Dior Eau Sauvage Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-dior-eau-sauvage-parfum`,
    urlPath: `/nuoc-hoa-nam-dior-eau-sauvage-parfum`,
    concentration: `Parfum`,
  },
  "egoiste": {
    title: `Chanel Égoïste EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Chanel Égoïste EDT nổi bật với quế theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng trước khi quyết định.`,
    h1: `Chanel Égoïste EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-chanel-egoiste`,
    urlPath: `/nuoc-hoa-nam-chanel-egoiste`,
    concentration: `EDT`,
    notesUsed: `quế`,
    scentDirection: `ấm và mềm`,
  },
  "egoiste-platinum": {
    title: `Chanel Égoïste Platinum EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Chanel Égoïste Platinum EDT phối oải hương theo hướng hoa thanh lịch; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Chanel Égoïste Platinum EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-chanel-egoiste-platinum`,
    urlPath: `/nuoc-hoa-nam-chanel-egoiste-platinum`,
    concentration: `EDT`,
    notesUsed: `oải hương`,
    scentDirection: `hoa thanh lịch`,
  },
  "elixir-des-merveilles": {
    title: `Hermès Elixir des Merveilles EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Hermès Elixir des Merveilles EDP được đánh giá theo phong cách mùi, độ dễ dùng và hoàn cảnh phù hợp; xem giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Hermès Elixir des Merveilles EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-hermes-elixir-des-merveilles`,
    urlPath: `/nuoc-hoa-nu-hermes-elixir-des-merveilles`,
    concentration: `EDP`,
  },
  "erba-pura": {
    title: `Xerjoff Erba Pura EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Xerjoff Erba Pura EDP được đánh giá theo phong cách mùi, độ dễ dùng và hoàn cảnh phù hợp; xem giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Xerjoff Erba Pura EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-xerjoff-erba-pura`,
    urlPath: `/nuoc-hoa-unisex-xerjoff-erba-pura`,
    concentration: `EDP`,
  },
  "eros-edp": {
    title: `Versace Eros EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Versace Eros EDP phối táo và vani theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng trước khi quyết định.`,
    h1: `Versace Eros EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-versace-eros-edp`,
    urlPath: `/nuoc-hoa-nam-versace-eros-edp`,
    concentration: `EDP`,
    notesUsed: `táo, vani`,
    scentDirection: `ấm và mềm`,
  },
  "explorer": {
    title: `Montblanc Explorer EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Montblanc Explorer EDP kết hợp cam bergamot và bạch dương theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Montblanc Explorer EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-montblanc-explorer`,
    urlPath: `/nuoc-hoa-nam-montblanc-explorer`,
    concentration: `EDP`,
    notesUsed: `cam bergamot, bạch dương`,
    scentDirection: `khô và sâu`,
  },
  "fahrenheit": {
    title: `Dior Fahrenheit EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Fahrenheit EDT nổi bật với hoa violet và da thuộc theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Dior Fahrenheit EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-dior-fahrenheit`,
    urlPath: `/nuoc-hoa-nam-dior-fahrenheit`,
    concentration: `EDT`,
    notesUsed: `hoa violet, da thuộc`,
    scentDirection: `khô và sâu`,
  },
  "fahrenheit-le-parfum": {
    title: `Dior Fahrenheit Le Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Fahrenheit Le Parfum phối rượu rum và da lộn theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Dior Fahrenheit Le Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-dior-fahrenheit-le-parfum`,
    urlPath: `/nuoc-hoa-nam-dior-fahrenheit-le-parfum`,
    concentration: `Parfum`,
    notesUsed: `rượu rum, da lộn`,
    scentDirection: `khô và sâu`,
  },
  "for-men": {
    title: `Coach For Men EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Coach For Men EDT kết hợp lê theo hướng tươi sáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng trước khi quyết định.`,
    h1: `Coach For Men EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-coach-for-men`,
    urlPath: `/nuoc-hoa-nam-coach-for-men`,
    concentration: `EDT`,
    notesUsed: `lê`,
    scentDirection: `tươi sáng`,
  },
  "ganymede": {
    title: `Marc-Antoine Barrois Ganymede EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Marc-Antoine Barrois Ganymede EDP nổi bật với khoáng chất và da lộn theo hướng tươi khoáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Marc-Antoine Barrois Ganymede EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-marc-antoine-barrois-ganymede`,
    urlPath: `/nuoc-hoa-unisex-marc-antoine-barrois-ganymede`,
    concentration: `EDP`,
    notesUsed: `khoáng chất, da lộn`,
    scentDirection: `tươi khoáng`,
  },
  "gentle-fluidity-gold": {
    title: `MFK Gentle Fluidity Gold EDP chính hãng: giá, review và mua ở đâu?`,
    description: `MFK Gentle Fluidity Gold EDP phối vani và nhục đậu khấu theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `MFK Gentle Fluidity Gold EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-maison-francis-kurkdjian-gentle-fluidity-gold`,
    urlPath: `/nuoc-hoa-unisex-maison-francis-kurkdjian-gentle-fluidity-gold`,
    concentration: `EDP`,
    notesUsed: `vani, nhục đậu khấu`,
    scentDirection: `ấm và mềm`,
  },
  "gentleman-reserve-privee": {
    title: `Givenchy Gentleman Réserve Privée EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Givenchy Gentleman Réserve Privée EDP kết hợp diên vĩ và hạt dẻ theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Givenchy Gentleman Réserve Privée EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-givenchy-gentleman-reserve-privee`,
    urlPath: `/nuoc-hoa-nam-givenchy-gentleman-reserve-privee`,
    concentration: `EDP`,
    notesUsed: `diên vĩ, hạt dẻ`,
    scentDirection: `ấm và mềm`,
  },
  "good-girl": {
    title: `Carolina Herrera Good Girl EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Carolina Herrera Good Girl EDP nổi bật với cacao theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Carolina Herrera Good Girl EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-carolina-herrera-good-girl`,
    urlPath: `/nuoc-hoa-nu-carolina-herrera-good-girl`,
    concentration: `EDP`,
    notesUsed: `cacao`,
    scentDirection: `ấm và mềm`,
  },
  "grand-soir": {
    title: `MFK Grand Soir EDP chính hãng: giá, review và mua ở đâu?`,
    description: `MFK Grand Soir EDP phối hổ phách và vani theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `MFK Grand Soir EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-maison-francis-kurkdjian-grand-soir`,
    urlPath: `/nuoc-hoa-unisex-maison-francis-kurkdjian-grand-soir`,
    concentration: `EDP`,
    notesUsed: `hổ phách, vani`,
    scentDirection: `ngọt ấm`,
  },
  "green-irish-tweed": {
    title: `Creed Green Irish Tweed EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Creed Green Irish Tweed EDP kết hợp cỏ xanh theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Creed Green Irish Tweed EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-creed-green-irish-tweed`,
    urlPath: `/nuoc-hoa-nam-creed-green-irish-tweed`,
    concentration: `EDP`,
    notesUsed: `cỏ xanh`,
    scentDirection: `khô và sâu`,
  },
  "grey-vetiver": {
    title: `Tom Ford Grey Vetiver EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Tom Ford Grey Vetiver EDP nổi bật với cỏ hương bài và bưởi theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Tom Ford Grey Vetiver EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-tom-ford-grey-vetiver`,
    urlPath: `/nuoc-hoa-nam-tom-ford-grey-vetiver`,
    concentration: `EDP`,
    notesUsed: `cỏ hương bài, bưởi`,
    scentDirection: `khô và sâu`,
  },
  "habit-rouge-eau-de-toilette": {
    title: `Guerlain Habit Rouge Eau de Toilette chính hãng: giá, review và mua ở đâu?`,
    description: `Guerlain Habit Rouge EDT phối da thuộc, cam và chanh theo hướng tươi sáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Guerlain Habit Rouge Eau de Toilette`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-guerlain-habit-rouge-eau-de-toilette`,
    urlPath: `/nuoc-hoa-nam-guerlain-habit-rouge-eau-de-toilette`,
    concentration: `EDT`,
    notesUsed: `da thuộc, cam, chanh`,
    scentDirection: `tươi sáng`,
  },
  "habit-rouge-parfum": {
    title: `Guerlain Habit Rouge Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Guerlain Habit Rouge Parfum kết hợp rượu rum, vani và hoắc hương theo hướng ấm và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Guerlain Habit Rouge Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-guerlain-habit-rouge-parfum`,
    urlPath: `/nuoc-hoa-nam-guerlain-habit-rouge-parfum`,
    concentration: `Parfum`,
    notesUsed: `rượu rum, vani, hoắc hương`,
    scentDirection: `ấm và sâu`,
  },
  "hacivat": {
    title: `Nishane Hacivat Extrait chính hãng: giá, review và mua ở đâu?`,
    description: `Nishane Hacivat Extrait nổi bật với dứa, rêu và rêu sồi theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Nishane Hacivat Extrait`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-nishane-hacivat`,
    urlPath: `/nuoc-hoa-unisex-nishane-hacivat`,
    concentration: `Extrait de Parfum`,
    notesUsed: `dứa, rêu, rêu sồi`,
    scentDirection: `khô và sâu`,
  },
  "halfeti": {
    title: `Penhaligon's Halfeti EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Penhaligon's Halfeti EDP phối trầm hương, hoa hồng và da thuộc theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Penhaligon's Halfeti EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-penhaligons-halfeti`,
    urlPath: `/nuoc-hoa-unisex-penhaligons-halfeti`,
    concentration: `EDP`,
    notesUsed: `trầm hương, hoa hồng, da thuộc`,
    scentDirection: `khô và sâu`,
  },
  "her-edp": {
    title: `Burberry Her EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Burberry Her EDP kết hợp dâu tây theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng trước khi quyết định.`,
    h1: `Burberry Her EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-burberry-her-edp`,
    urlPath: `/nuoc-hoa-nu-burberry-her-edp`,
    concentration: `EDP`,
    notesUsed: `dâu tây`,
    scentDirection: `ấm và mềm`,
  },
  "herod": {
    title: `Parfums de Marly Herod EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Parfums de Marly Herod EDP nổi bật với khói, thuốc lá và vani theo hướng ấm và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Parfums de Marly Herod EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-parfums-de-marly-herod`,
    urlPath: `/nuoc-hoa-nam-parfums-de-marly-herod`,
    concentration: `EDP`,
    notesUsed: `khói, thuốc lá, vani, quế`,
    scentDirection: `ấm và sâu`,
  },
  "homme-cologne": {
    title: `Dior Homme Cologne chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Homme Cologne phối bưởi và chanh theo hướng tươi sáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng trước khi quyết định.`,
    h1: `Dior Homme Cologne`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-dior-homme-cologne`,
    urlPath: `/nuoc-hoa-nam-dior-homme-cologne`,
    concentration: `Cologne`,
    notesUsed: `bưởi, chanh`,
    scentDirection: `tươi sáng`,
  },
  "homme-intense": {
    title: `Dior Homme Intense EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Homme Intense EDP kết hợp diên vĩ theo hướng sạch và thanh; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Dior Homme Intense EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-dior-homme-intense`,
    urlPath: `/nuoc-hoa-nam-dior-homme-intense`,
    concentration: `EDP`,
    notesUsed: `diên vĩ`,
    scentDirection: `sạch và thanh`,
  },
  "homme-parfum": {
    title: `Dior Homme Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Homme Parfum nổi bật với diên vĩ và da thuộc theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Dior Homme Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-dior-homme-parfum`,
    urlPath: `/nuoc-hoa-nam-dior-homme-parfum`,
    concentration: `Parfum`,
    notesUsed: `diên vĩ, da thuộc`,
    scentDirection: `khô và sâu`,
  },
  "homme-sport-2021": {
    title: `Dior Homme Sport (2021) EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Homme Sport (2021) EDT phối cam, chanh và tiêu theo hướng tươi sáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Dior Homme Sport (2021) EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-dior-homme-sport-2021`,
    urlPath: `/nuoc-hoa-nam-dior-homme-sport-2021`,
    concentration: `EDT`,
    notesUsed: `cam, chanh, tiêu`,
    scentDirection: `tươi sáng`,
  },
  "hundred-silent-ways": {
    title: `Nishane Hundred Silent Ways Extrait chính hãng: giá, review và mua ở đâu?`,
    description: `Nishane Hundred Silent Ways Extrait kết hợp trái cây, vani và hoa nhài theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Nishane Hundred Silent Ways Extrait`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-nishane-hundred-silent-ways`,
    urlPath: `/nuoc-hoa-unisex-nishane-hundred-silent-ways`,
    concentration: `Extrait de Parfum`,
    notesUsed: `trái cây, vani, hoa nhài, đào`,
    scentDirection: `ngọt ấm`,
  },
  "hypnotic-poison": {
    title: `Dior Hypnotic Poison EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Dior Hypnotic Poison EDT nổi bật với vani, hạnh nhân và dừa theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Dior Hypnotic Poison EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-dior-hypnotic-poison`,
    urlPath: `/nuoc-hoa-nu-dior-hypnotic-poison`,
    concentration: `EDT`,
    notesUsed: `vani, hạnh nhân, dừa`,
    scentDirection: `ngọt ấm`,
  },
  "imagination": {
    title: `Louis Vuitton Imagination EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Louis Vuitton Imagination EDP phối trà, cam và chanh theo hướng tươi khoáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Louis Vuitton Imagination EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-louis-vuitton-imagination`,
    urlPath: `/nuoc-hoa-nam-louis-vuitton-imagination`,
    concentration: `EDP`,
    notesUsed: `trà, cam, chanh, ambroxan`,
    scentDirection: `tươi khoáng`,
  },
  "infusion-diris": {
    title: `Prada Infusion d'Iris EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Prada Infusion d'Iris EDP kết hợp diên vĩ và gỗ tuyết tùng theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Prada Infusion d'Iris EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-prada-infusion-diris`,
    urlPath: `/nuoc-hoa-nu-prada-infusion-diris`,
    concentration: `EDP`,
    notesUsed: `diên vĩ, gỗ tuyết tùng`,
    scentDirection: `khô và sâu`,
  },
  "insolence-edp": {
    title: `Guerlain Insolence EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Guerlain Insolence EDP nổi bật với diên vĩ theo hướng sạch và thanh; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Guerlain Insolence EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-guerlain-insolence-edp`,
    urlPath: `/nuoc-hoa-nu-guerlain-insolence-edp`,
    concentration: `EDP`,
    notesUsed: `diên vĩ`,
    scentDirection: `sạch và thanh`,
  },
  "instant-crush": {
    title: `Mancera Instant Crush EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Mancera Instant Crush EDP phối nghệ tây, vani và hổ phách theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Mancera Instant Crush EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-mancera-instant-crush`,
    urlPath: `/nuoc-hoa-unisex-mancera-instant-crush`,
    concentration: `EDP`,
    notesUsed: `nghệ tây, vani, hổ phách`,
    scentDirection: `ngọt ấm`,
  },
  "interlude-man": {
    title: `Amouage Interlude Man EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Amouage Interlude Man EDP kết hợp khói và trầm hương theo hướng khô và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Amouage Interlude Man EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-amouage-interlude-man`,
    urlPath: `/nuoc-hoa-nam-amouage-interlude-man`,
    concentration: `EDP`,
    notesUsed: `khói, trầm hương`,
    scentDirection: `khô và sâu`,
  },
  "jadore-edp": {
    title: `Dior J'adore EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Dior J'adore EDP nổi bật với hoa trắng, hoa mộc lan và lê theo hướng hoa rõ nét; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Dior J'adore EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-dior-jadore-edp`,
    urlPath: `/nuoc-hoa-nu-dior-jadore-edp`,
    concentration: `EDP`,
    notesUsed: `hoa trắng, hoa mộc lan, lê`,
    scentDirection: `hoa rõ nét`,
  },
  "jazz-club": {
    title: `Maison Margiela Replica Jazz Club EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Replica Jazz Club EDT phối rượu rum, thuốc lá và vani theo hướng ấm và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Maison Margiela Replica Jazz Club EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-maison-margiela-jazz-club`,
    urlPath: `/nuoc-hoa-nam-maison-margiela-jazz-club`,
    concentration: `Replica EDT`,
    notesUsed: `rượu rum, thuốc lá, vani, khói`,
    scentDirection: `ấm và sâu`,
  },
  "jpg-classique-edt": {
    title: `Jean Paul Gaultier Classique EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Jean Paul Gaultier Classique EDT kết hợp hoa cam, cam và vani theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Jean Paul Gaultier Classique EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-jean-paul-gaultier-jpg-classique-edt`,
    urlPath: `/nuoc-hoa-nu-jean-paul-gaultier-jpg-classique-edt`,
    concentration: `EDT`,
    notesUsed: `hoa cam, cam, vani`,
    scentDirection: `ấm và mềm`,
  },
  "jpg-la-belle-edp": {
    title: `Jean Paul Gaultier La Belle EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Jean Paul Gaultier La Belle EDP nổi bật với lê, vani và đào theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Jean Paul Gaultier La Belle EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-jean-paul-gaultier-jpg-la-belle-edp`,
    urlPath: `/nuoc-hoa-nu-jean-paul-gaultier-jpg-la-belle-edp`,
    concentration: `EDP`,
    notesUsed: `lê, vani, đào`,
    scentDirection: `ngọt ấm`,
  },
  "jpg-la-belle-le-parfum": {
    title: `Jean Paul Gaultier La Belle Le Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Jean Paul Gaultier La Belle Le Parfum phối lê, đậu tonka và vani theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Jean Paul Gaultier La Belle Le Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-jean-paul-gaultier-jpg-la-belle-le-parfum`,
    urlPath: `/nuoc-hoa-nu-jean-paul-gaultier-jpg-la-belle-le-parfum`,
    concentration: `Le Parfum`,
    notesUsed: `lê, đậu tonka, vani`,
    scentDirection: `ngọt ấm`,
  },
  "jpg-le-beau-le-parfum": {
    title: `Jean Paul Gaultier Le Beau Le Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Jean Paul Gaultier Le Beau Le Parfum kết hợp dừa, dứa và hương biển theo hướng tươi khoáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Jean Paul Gaultier Le Beau Le Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-jean-paul-gaultier-jpg-le-beau-le-parfum`,
    urlPath: `/nuoc-hoa-nam-jean-paul-gaultier-jpg-le-beau-le-parfum`,
    concentration: `Le Parfum (Intense)`,
    notesUsed: `dừa, dứa, hương biển`,
    scentDirection: `tươi khoáng`,
  },
  "jpg-le-male-edt": {
    title: `Jean Paul Gaultier Le Male EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Jean Paul Gaultier Le Male EDT nổi bật với oải hương và vani theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Jean Paul Gaultier Le Male EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-jean-paul-gaultier-jpg-le-male-edt`,
    urlPath: `/nuoc-hoa-nam-jean-paul-gaultier-jpg-le-male-edt`,
    concentration: `EDT`,
    notesUsed: `oải hương, vani`,
    scentDirection: `ấm và mềm`,
  },
  "jpg-le-male-elixir": {
    title: `Jean Paul Gaultier Le Male Elixir Parfum chính hãng: giá và review`,
    description: `Jean Paul Gaultier Le Male Elixir Parfum phối mật ong và vani theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Jean Paul Gaultier Le Male Elixir Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-jean-paul-gaultier-jpg-le-male-elixir`,
    urlPath: `/nuoc-hoa-nam-jean-paul-gaultier-jpg-le-male-elixir`,
    concentration: `Elixir Parfum`,
    notesUsed: `mật ong, vani`,
    scentDirection: `ngọt ấm`,
  },
  "jpg-le-male-le-parfum": {
    title: `Jean Paul Gaultier Le Male Le Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Jean Paul Gaultier Le Male Le Parfum kết hợp diên vĩ, vani và bạch đậu khấu theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Jean Paul Gaultier Le Male Le Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-jean-paul-gaultier-jpg-le-male-le-parfum`,
    urlPath: `/nuoc-hoa-nam-jean-paul-gaultier-jpg-le-male-le-parfum`,
    concentration: `Le Parfum`,
    notesUsed: `diên vĩ, vani, bạch đậu khấu`,
    scentDirection: `ấm và mềm`,
  },
  "jpg-ultra-male": {
    title: `Jean Paul Gaultier Ultra Male EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Jean Paul Gaultier Ultra Male EDT nổi bật với lê, vani và quế theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Jean Paul Gaultier Ultra Male EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-jean-paul-gaultier-jpg-ultra-male`,
    urlPath: `/nuoc-hoa-nam-jean-paul-gaultier-jpg-ultra-male`,
    concentration: `EDT Intense`,
    notesUsed: `lê, vani, quế`,
    scentDirection: `ngọt ấm`,
  },
  "khamrah": {
    title: `Lattafa Khamrah EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Lattafa Khamrah EDP phối nhục đậu khấu, quế và vani theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Lattafa Khamrah EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-lattafa-khamrah`,
    urlPath: `/nuoc-hoa-unisex-lattafa-khamrah`,
    concentration: `EDP`,
    notesUsed: `nhục đậu khấu, quế, vani, táo`,
    scentDirection: `ngọt ấm`,
  },
  "l-homme-ideal-eau-de-parfum": {
    title: `Guerlain L’Homme Idéal Eau de Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Guerlain L’Homme Idéal EDP kết hợp anh đào và hạnh nhân theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Guerlain L’Homme Idéal Eau de Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-guerlain-l-homme-ideal-eau-de-parfum`,
    urlPath: `/nuoc-hoa-nam-guerlain-l-homme-ideal-eau-de-parfum`,
    concentration: `EDP`,
    notesUsed: `anh đào, hạnh nhân`,
    scentDirection: `ngọt ấm`,
  },
  "l-interdit-eau-de-parfum": {
    title: `Givenchy L'Interdit EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Givenchy L'Interdit EDP nổi bật với hoa huệ, hoa cam và cam theo hướng hoa rõ nét; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Givenchy L'Interdit EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-givenchy-l-interdit-eau-de-parfum`,
    urlPath: `/nuoc-hoa-nu-givenchy-l-interdit-eau-de-parfum`,
    concentration: `EDP`,
    notesUsed: `hoa huệ, hoa cam, cam, hoắc hương`,
    scentDirection: `hoa rõ nét`,
  },
  "l-interdit-eau-de-parfum-rouge": {
    title: `Givenchy L'Interdit Rouge EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Givenchy L'Interdit Rouge EDP phối hoa huệ, gừng và cam máu theo hướng hoa thanh lịch; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Givenchy L'Interdit Rouge EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-givenchy-l-interdit-eau-de-parfum-rouge`,
    urlPath: `/nuoc-hoa-nu-givenchy-l-interdit-eau-de-parfum-rouge`,
    concentration: `EDP`,
    notesUsed: `hoa huệ, gừng, cam máu`,
    scentDirection: `hoa thanh lịch`,
  },
  "la-nuit-de-lhomme": {
    title: `YSL La Nuit de L’Homme EDT chính hãng: giá, review và mua ở đâu?`,
    description: `YSL La Nuit de L’Homme EDT kết hợp bạch đậu khấu, oải hương và gỗ tuyết tùng theo hướng gỗ–cay sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `YSL La Nuit de L’Homme EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-ysl-la-nuit-de-lhomme`,
    urlPath: `/nuoc-hoa-nam-ysl-la-nuit-de-lhomme`,
    concentration: `EDT`,
    notesUsed: `bạch đậu khấu, oải hương, gỗ tuyết tùng`,
    scentDirection: `gỗ–cay sâu`,
  },
  "la-nuit-de-lhomme-bleu-electrique": {
    title: `YSL La Nuit de L’Homme Bleu Électrique EDT chính hãng: giá và review`,
    description: `YSL La Nuit de L’Homme Bleu Électrique EDT phối oải hương, bạch đậu khấu và gừng; xem review, giá tham khảo và tiêu chí chọn nơi mua chính hãng.`,
    h1: `YSL La Nuit de L’Homme Bleu Électrique EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-ysl-la-nuit-de-lhomme-bleu-electrique`,
    urlPath: `/nuoc-hoa-nam-ysl-la-nuit-de-lhomme-bleu-electrique`,
    concentration: `EDT`,
    notesUsed: `oải hương, bạch đậu khấu, gừng`,
    scentDirection: `hoa thanh lịch`,
  },
  "la-vie-est-belle": {
    title: `Lancôme La Vie Est Belle EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Lancôme La Vie Est Belle EDP phối vani và hoắc hương theo hướng ấm và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Lancôme La Vie Est Belle EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-lancome-la-vie-est-belle`,
    urlPath: `/nuoc-hoa-nu-lancome-la-vie-est-belle`,
    concentration: `EDP`,
    notesUsed: `vani, hoắc hương`,
    scentDirection: `ấm và sâu`,
  },
  "layton": {
    title: `Parfums de Marly Layton EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Parfums de Marly Layton EDP kết hợp vani, táo và oải hương theo hướng ấm và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Parfums de Marly Layton EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-unisex-parfums-de-marly-layton`,
    urlPath: `/nuoc-hoa-unisex-parfums-de-marly-layton`,
    concentration: `EDP`,
    notesUsed: `vani, táo, oải hương, gỗ đàn hương`,
    scentDirection: `ấm và sâu`,
  },
  "le-parfum-elie-saab": {
    title: `Elie Saab Le Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Elie Saab Le Parfum nổi bật với mật ong, hoa cam và cam theo hướng ấm và mềm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Elie Saab Le Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-elie-saab-le-parfum-elie-saab`,
    urlPath: `/nuoc-hoa-nu-elie-saab-le-parfum-elie-saab`,
    concentration: `EDP`,
    notesUsed: `mật ong, hoa cam, cam`,
    scentDirection: `ấm và mềm`,
  },
  "le-parfum-lolita": {
    title: `Lolita Lempicka Le Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Lolita Lempicka Le Parfum phối táo, cam và anh đào theo hướng tươi sáng; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Lolita Lempicka Le Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-lolita-lempicka-le-parfum-lolita`,
    urlPath: `/nuoc-hoa-nu-lolita-lempicka-le-parfum-lolita`,
    concentration: `Le Parfum`,
    notesUsed: `táo, cam, anh đào`,
    scentDirection: `tươi sáng`,
  },
  "leau-dissey-pour-homme": {
    title: `Issey Miyake L’Eau d'Issey Pour Homme EDT chính hãng: giá và review`,
    description: `Issey Miyake L’Eau d'Issey Pour Homme EDT kết hợp yuzu và hoa sen theo hướng hoa thanh lịch; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Issey Miyake L’Eau d'Issey Pour Homme EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-issey-miyake-leau-dissey-pour-homme`,
    urlPath: `/nuoc-hoa-nam-issey-miyake-leau-dissey-pour-homme`,
    concentration: `EDT`,
    notesUsed: `yuzu, hoa sen`,
    scentDirection: `hoa thanh lịch`,
  },
  "l-heure-bleue-eau-de-parfum": {
    title: `Guerlain L'Heure Bleue Eau de Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Guerlain L'Heure Bleue EDP nổi bật với diên vĩ theo hướng sạch và thanh; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Guerlain L'Heure Bleue Eau de Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-guerlain-l-heure-bleue-eau-de-parfum`,
    urlPath: `/nuoc-hoa-nu-guerlain-l-heure-bleue-eau-de-parfum`,
    concentration: `EDP`,
    notesUsed: `diên vĩ`,
    scentDirection: `sạch và thanh`,
  },
  "l-heure-bleue-eau-de-toilette": {
    title: `Guerlain L’Heure Bleue EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Guerlain L’Heure Bleue EDT được đánh giá theo phong cách mùi, độ dễ dùng và hoàn cảnh phù hợp; xem giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Guerlain L’Heure Bleue EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-guerlain-l-heure-bleue-eau-de-toilette`,
    urlPath: `/nuoc-hoa-nu-guerlain-l-heure-bleue-eau-de-toilette`,
    concentration: `EDT`,
  },
  "lhomme": {
    title: `Prada L’Homme EDT chính hãng: giá, review và mua ở đâu?`,
    description: `Prada L’Homme EDT kết hợp diên vĩ theo hướng sạch và thanh; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng trước khi quyết định.`,
    h1: `Prada L’Homme EDT`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-prada-lhomme`,
    urlPath: `/nuoc-hoa-nam-prada-lhomme`,
    concentration: `EDT`,
    notesUsed: `diên vĩ`,
    scentDirection: `sạch và thanh`,
  },
  "lhomme-ideal-parfum": {
    title: `Guerlain L’Homme Idéal Parfum chính hãng: giá, review và mua ở đâu?`,
    description: `Guerlain L’Homme Idéal Parfum nổi bật với hạnh nhân, da thuộc và hoắc hương theo hướng ấm và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Guerlain L’Homme Idéal Parfum`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-guerlain-lhomme-ideal-parfum`,
    urlPath: `/nuoc-hoa-nam-guerlain-lhomme-ideal-parfum`,
    concentration: `Parfum`,
    notesUsed: `hạnh nhân, da thuộc, hoắc hương`,
    scentDirection: `ấm và sâu`,
  },
  "lhomme-intense": {
    title: `Prada L’Homme Intense EDP chính hãng: giá, review và mua ở đâu?`,
    description: `Prada L’Homme Intense EDP phối diên vĩ, da thuộc và đậu tonka theo hướng ấm và sâu; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `Prada L’Homme Intense EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nam-prada-lhomme-intense`,
    urlPath: `/nuoc-hoa-nam-prada-lhomme-intense`,
    concentration: `EDP`,
    notesUsed: `diên vĩ, da thuộc, đậu tonka`,
    scentDirection: `ấm và sâu`,
  },
  "libre-edp": {
    title: `YSL Libre EDP chính hãng: giá, review và mua ở đâu?`,
    description: `YSL Libre EDP kết hợp oải hương, hoa cam và cam theo hướng hoa rõ nét; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `YSL Libre EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-ysl-libre-edp`,
    urlPath: `/nuoc-hoa-nu-ysl-libre-edp`,
    concentration: `EDP`,
    notesUsed: `oải hương, hoa cam, cam, vani`,
    scentDirection: `hoa rõ nét`,
  },
  "libre-intense": {
    title: `YSL Libre Intense EDP chính hãng: giá, review và mua ở đâu?`,
    description: `YSL Libre Intense EDP nổi bật với vani, oải hương và đậu tonka theo hướng ngọt ấm; xem review, giá tham khảo cùng tiêu chí chọn nơi mua chính hãng.`,
    h1: `YSL Libre Intense EDP`,
    canonical: `https://www.maisondeson.com/nuoc-hoa-nu-ysl-libre-intense`,
    urlPath: `/nuoc-hoa-nu-ysl-libre-intense`,
    concentration: `EDP`,
    notesUsed: `vani, oải hương, đậu tonka`,
    scentDirection: `ngọt ấm`,
  },
};

export function getProductSeoMetadata(
  productId: string | undefined | null,
): ProductSeoMetadata | null {
  if (!productId) return null;
  const key = resolveProductId(productId);
  return PRODUCT_SEO_METADATA[key] || null;
}

export function hasProductCommercialSeo(productId: string | undefined | null): boolean {
  return getProductSeoMetadata(productId) !== null;
}
