Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.16.jpg" -OutFile "public\images\products\no-19-eau-de-toilette-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.88588.jpg" -OutFile "public\images\products\vanilla-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.44894.jpg" -OutFile "public\images\products\bloom-edp-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.42260.jpg" -OutFile "public\images\products\armaf-effects-of-uniq-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.43632.jpg" -OutFile "public\images\products\black-phantom-by-kilian-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.70189.jpg" -OutFile "public\images\products\blanche-bete-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.70189.jpg" -OutFile "public\images\products\byredo-blanche-edp-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.83015.jpg" -OutFile "public\images\products\chloe-atelier-des-fleurs-rosa-damascena-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.57336.jpg" -OutFile "public\images\products\chloe-atelier-des-fleurs-santalum-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.4322.jpg" -OutFile "public\images\products\creed-love-in-white-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.40031.jpg" -OutFile "public\images\products\ex-nihilo-blue-talisman-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.59532.jpg" -OutFile "public\images\products\giorgio-armani-acqua-di-gio-profondo-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.54822.jpg" -OutFile "public\images\products\gritti-tutu-extrait-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.68578.jpg" -OutFile "public\images\products\gucci-flora-gorgeous-gardenia-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.83015.jpg" -OutFile "public\images\products\guerlain-aqua-allegoria-forte-rosa-palissandro-edp-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.79228.jpg" -OutFile "public\images\products\guerlain-aqua-allegoria-nerolia-vetiver-edp-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.66360.jpg" -OutFile "public\images\products\guerlain-aqua-allegoria-nettare-di-sole-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.42747.jpg" -OutFile "public\images\products\hermes-bleue-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.55983.jpg" -OutFile "public\images\products\hermes-twilly-eau-poivree-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.64015.jpg" -OutFile "public\images\products\jimmy-choo-i-want-choo-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.15924.jpg" -OutFile "public\images\products\kilan-good-girl-gone-bad-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.56402.jpg" -OutFile "public\images\products\kilian-rolling-in-love-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.57336.jpg" -OutFile "public\images\products\lorchestre-piano-santal-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.1834.jpg" -OutFile "public\images\products\lalique-encre-noir-edt-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.12201.jpg" -OutFile "public\images\products\le-labo-santal-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.16.jpg" -OutFile "public\images\products\mcm-zen-elephant-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.83015.jpg" -OutFile "public\images\products\maison-francis-kurkdjian-kurky-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.42670.jpg" -OutFile "public\images\products\mancera-sicily-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.15211.jpg" -OutFile "public\images\products\mancera-cedrat-boise-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.113241.jpg" -OutFile "public\images\products\miss-dior-essence-new-2025-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.55858.jpg" -OutFile "public\images\products\moschino-toy-boy-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.66097.jpg" -OutFile "public\images\products\musk-kashmir-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.62036.jpg" -OutFile "public\images\products\my-way-edp-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.73075.jpg" -OutFile "public\images\products\nar-cristal-edp-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.36679.jpg" -OutFile "public\images\products\nar-poudree-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.6575.jpg" -OutFile "public\images\products\narciso-for-her-edp-intense-new-2025-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.88936.jpg" -OutFile "public\images\products\narciso-musc-nude-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.84201.jpg" -OutFile "public\images\products\narciso-rodriguez-all-of-me-floral-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.14319.jpg" -OutFile "public\images\products\narciso-rodriguez-for-her-eau-de-parfum-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.64948.jpg" -OutFile "public\images\products\oud-forever-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.46038.jpg" -OutFile "public\images\products\paco-pure-xs-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.96023.jpg" -OutFile "public\images\products\parfums-de-marly-palatine-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.78574.jpg" -OutFile "public\images\products\parfums-de-marly-valaya-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.46661.jpg" -OutFile "public\images\products\parfums-de-marly-valaya-exclusif-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.62320.jpg" -OutFile "public\images\products\rj-burlington-1819-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.31623.jpg" -OutFile "public\images\products\replica-by-the-fireplace-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.20542.jpg" -OutFile "public\images\products\replica-lazy-sunday-morning-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.31872.jpg" -OutFile "public\images\products\the-noir-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.53742.jpg" -OutFile "public\images\products\thomas-kosmala-no-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.1018.jpg" -OutFile "public\images\products\tom-ford-black-orchid-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.631.jpg" -OutFile "public\images\products\versace-bright-crystal-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.92647.jpg" -OutFile "public\images\products\versace-eros-energy-edp-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.52180.jpg" -OutFile "public\images\products\versace-eros-flame-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.44763.jpg" -OutFile "public\images\products\versce-pour-homme-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.6310.jpg" -OutFile "public\images\products\xerjoff-casamorati-mefisto-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.70424.jpg" -OutFile "public\images\products\xerjoff-torino-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.100628.jpg" -OutFile "public\images\products\ysl-black-opium-glitter-edp-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.62318.jpg" -OutFile "public\images\products\ysl-libre-intense-edp-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.10464.jpg" -OutFile "public\images\products\ysl-y-eau-de-parfum-main.jpg" -ErrorAction SilentlyContinue
Invoke-WebRequest -Uri "https://fimgs.net/mdimg/perfume/o.14319.jpg" -OutFile "public\images\products\ventus-for-her-main.jpg" -ErrorAction SilentlyContinue
